import { chromium } from "playwright";
import { mkdirSync } from "fs";
mkdirSync("/tmp/flow1-stills", { recursive: true });
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1280, height: 800 } });
await context.addInitScript((pk) => localStorage.setItem("zkburn.john.pk", pk), process.env.JOHN3_PK);
const page = await context.newPage();
const pause = (ms) => new Promise((r) => setTimeout(r, ms));
const shot = (n) => page.screenshot({ path: `/tmp/flow1-stills/${n}.png` });

await page.goto("http://localhost:3100/demo");
await pause(1500);
await shot("01-hub");
await page.getByRole("button", { name: "Go to John's Portal" }).click();
await page.waitForURL("**/john/portal");
await pause(1500);
await shot("02-portal");
await page.getByRole("button", { name: "Generate My Anonymous ID" }).click();
await pause(300);
await shot("03-authenticating");
await page.waitForSelector("svg[height='192']", { timeout: 60000 });
await pause(800);
await shot("04-qr");
await pause(1200);
await shot("05-qr");
await page.getByRole("button", { name: "Simulate proof (demo mode)" }).click();
await pause(1200);
await shot("06-registering");
const idBox = page.locator("p.font-mono.break-all");
await idBox.waitFor({ timeout: 90000 });
await pause(1500); // let status/badge load
await shot("07-registered");
console.log("johnId:", (await idBox.textContent()).trim());
await browser.close();
